spring.data.mongodb.uri=mongodb+srv://sri812469_db_user:LkgwPmAtl4aKm7uS@cluster0.izkqmab.mongodb.net/hms?retryWrites=true&w=majority&appName=Cluster0
server.port=5000
# Database Password: LkgwPmAtl4aKm7uS
# Mongo User: sri812469_db_user